---
- name: Run a script
  hosts: all

  tasks:
  - name: Run script
    shell: ./test.sh >> test.log
    args:
      chdir: /tmp/script/  #To chnage dir before running script
      creates: test.log
