---
- name: Cron Setup
  hosts: all

  tasks:
  - name: Add Cron Job
    cron:
      name: Run Test Script
      minute: 30
      hour: 20
      day: 15
      month: "*"
      weekday: "*"
      user: paul
      job: /tmp/script/test.sh
      disabled: yes  #This parameter disables the cron job without deleting it. It will still exist in the cron configuration but will not run until it is enabled. This is useful if you want to set up the job in advance but hold off on running it.
