---
- name: Kill a process
  hosts: all

  tasks:
  - name: Find a process and kill it
    ignore_errors: yes
    shell: "pgrep nginx | xargs kill"  #This command first searches for the nginx process using pgrep nginx and then kills any matching processes with xargs kill.

  - name: Start the service
    service:
      name: nginx
      state: started
